# Generated by Django 4.2.4 on 2023-08-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, help_text='size of screen [inch]', max_digits=4),
        ),
    ]
