# Generated by Django 4.2.4 on 2023-08-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_alter_mobile_available_alter_mobile_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
